## Numpy Assignment

### -------------------------------------------------------------------------------

In [14]:
##Consider the below code to answer further questions:
import numpy as np
list_ = ['1','2','3','4','5']
array_list = np.array(object = list_)

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
#### to print the data types of both the variables.

Ans -> Variable 'list_' has data type as list while variable 'array_list' has data type as numpy.ndarray.
The main difference is that NumPy arrays are much faster and have strict requirements on the homogeneity of the objects. For example, a NumPy array of strings can only contain strings and no other data types, but a Python list can contain a mixture of strings, numbers, booleans and other objects.

In [25]:
print(list_)
print(type(list_))

['1', '2', '3', '4', '5']
<class 'list'>


In [26]:
print(array_list)
print(type(array_list))

['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>


### -------------------------------------------------------------------------------

#### Q2. Write a code to print the data type of each and every element of both the variables list_ and
#### arra_list.

In [21]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [32]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### -------------------------------------------------------------------------------

#### Q3. Considering the following changes in the variable, array_list:
#### array_list = np.array(object = list_, dtype = int)
#### Will there be any difference in the data type of the elements present in both the variables, list_ and
#### arra_list? If so then print the data types of each and every element present in both the variables, list_
#### and arra_list.

Ans -> Yes, data type of all the elements inside numpy array would be changed to type int64 as specified in the passed parameter.

In [27]:
array_list = np.array(object = list_, dtype = int)

In [28]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [33]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


### -------------------------------------------------------------------------------

In [10]:
##Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

#### Q4. Write a code to find the following characteristics of variable, num_array:
#### (i) shape
#### (ii) size

In [13]:
print(num_array)

[[1 2 3]
 [4 5 6]]


In [11]:
num_array.shape

(2, 3)

In [12]:
num_array.size

6

### -------------------------------------------------------------------------------

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
#### creation function.
#### [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [9]:
A = np.zeros((3,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### -------------------------------------------------------------------------------

#### Q6. Create an identity matrix of shape (5,5) using numpy functions?
#### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [3]:
I = np.eye(5)

In [4]:
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
